// Copyright (c) 2020 SafetyCulture Pty Ltd. All Rights Reserved.

package plugin

import (
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/SafetyCulture/s12-proto/protobuf/validation/plan"
)

// Standard library dependencies.
const (
	fmtPackage       = protogen.GoImportPath("fmt")
	timePackage      = protogen.GoImportPath("time")
	mathPackage      = protogen.GoImportPath("math")
	regexpPackage    = protogen.GoImportPath("regexp")
	stringsPackage   = protogen.GoImportPath("strings")
	utfPackage       = protogen.GoImportPath("unicode/utf8")
	normPackage      = protogen.GoImportPath("golang.org/x/text/unicode/norm")
	transformPackage = protogen.GoImportPath("golang.org/x/text/transform")
)

// Other library dependencies.
const (
	s12protoPackage = protogen.GoImportPath("github.com/SafetyCulture/s12-proto/s12/protobuf/proto")
)

// Some global vars for regex generations
var regexGeneratedFile *protogen.GeneratedFile
var regexHashLib = make(map[string]struct{})

// Validator plugin version
var validatorVersion = "v2.7.2"

// Write a preamble in the auto generated files
func genGeneratedHeader(gen *protogen.Plugin, g *protogen.GeneratedFile, f *protogen.File) {
	g.P("// Code generated by protoc-gen-govalidator. DO NOT EDIT.")
	g.P("// versions:")
	protocVersion := "(unknown)"
	if v := gen.Request.GetCompilerVersion(); v != nil {
		protocVersion = fmt.Sprintf("v%v.%v.%v", v.GetMajor(), v.GetMinor(), v.GetPatch())
		if s := v.GetSuffix(); s != "" {
			protocVersion += "-" + s
		}
	}
	g.P("// \tprotoc-gen-govalidator ", validatorVersion)
	g.P("// \tprotoc                 ", protocVersion)

	if f.Proto.GetOptions().GetDeprecated() {
		g.P("// ", f.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", f.Desc.Path())
	}
	g.P()
}

// GenerateFile generates the validator.pb.go file
func GenerateFile(p *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	p.SupportedFeatures |= uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	filename := file.GeneratedFilenamePrefix + ".validator.pb.go"
	g := p.NewGeneratedFile(filename, file.GoImportPath)

	// Add preamble and version for validator.pb.go
	genGeneratedHeader(p, g, file)

	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// Generate a blank import statement if not used by any validation functions,
	// as we still want to register the protobuf validation types for the Reflection API.
	g.Import(s12protoPackage)

	// Also prepare a separate file for regex patterns
	// Writing these to a separate file otherwise the generation logic would be confusing
	// and require two iterations for each message field (one to generate the regex, one for the rest)
	regexFilename := file.GeneratedFilenamePrefix + ".validator_regex.pb.go"
	regexGeneratedFile = p.NewGeneratedFile(regexFilename, file.GoImportPath)

	// Add preamble and version for validator_regex.pb.go
	genGeneratedHeader(p, regexGeneratedFile, file)
	regexGeneratedFile.P()
	regexGeneratedFile.P("package ", file.GoPackageName)
	regexGeneratedFile.P()
	regexGeneratedFile.Import(s12protoPackage)

	for _, msg := range plan.BuildFile(file).Messages {
		genLegacyRegexVars(g, msg)
		genValidateFunc(g, msg)
		g.P()
	}

	return g
}

// addRegexVar declares the pattern as a compiled package-level variable and
// returns the name it was given. Fields sharing a pattern share the variable.
func addRegexVar(fieldName, pattern string) string {

	// Generate a unique hash based on regex pattern so we can reuse patterns
	hash := md5.New()
	hash.Write([]byte(pattern))
	name := hex.EncodeToString(hash.Sum(nil))

	// Check if this is a duplicate regex pattern in which case we can reuse the regex
	if _, found := regexHashLib[name]; found {
		regexGeneratedFile.P("// " + fieldName + " is using regex " + name)
		return name
	}

	regexGeneratedFile.P("// Pattern for " + fieldName)
	regexGeneratedFile.P("const ", "_regex_val_", name, " = `", pattern, "`")
	regexGeneratedFile.P("var ", "_regex_", name, " = ", regexpPackage.Ident("MustCompile"), "(_regex_val_", name, ")")

	// Keep track of this regex to avoid duplicates
	regexHashLib[name] = struct{}{}
	return name
}

// Generator for legacy regex validator
func genLegacyRegexVars(g *protogen.GeneratedFile, msg *plan.Message) {
	for _, r := range msg.LegacyRegex {
		g.P("const ", "_regex_val_", r.Proto.GoIdent, " = `", r.Pattern, "`")
		g.P("var ", "_regex_", r.Proto.GoIdent, " = ", regexpPackage.Ident("MustCompile"), "(_regex_val_", r.Proto.GoIdent, ")")
	}
	for _, innerMsg := range msg.Nested {
		genLegacyRegexVars(g, innerMsg)
	}
}

func genValidateFunc(g *protogen.GeneratedFile, msg *plan.Message) {
	g.P("func (m *", msg.Proto.GoIdent.GoName, `) Validate() error {`)
	for _, f := range msg.Fields {
		varName := "m." + f.Proto.GoName

		if v := f.RepeatedLenGte; v >= 0 {
			g.P("if !(len(", varName, ") >= ", v, ") {")
			errStr := fmt.Sprintf(`be greater than or equal to %d`, v)
			genLenErrorString(g, varName, f.Name, errStr)
			g.P("}")
		}

		if v := f.RepeatedLenLte; v >= 0 {
			g.P("if !(len(", varName, ") <= ", v, ") {")
			errStr := fmt.Sprintf(`be lesser than or equal to %d`, v)
			genLenErrorString(g, varName, f.Name, errStr)
			g.P("}")
		}

		if f.Loop {
			g.P("for _, item := range ", varName, "{")
			varName = "item"
		}

		if f.Unsupported != "" {
			g.P("// ", f.Unsupported)
			continue
		}

		if f.Oneof {
			g.P("if x, ok := m.", f.Proto.Oneof.GoName, ".(*", g.QualifiedGoIdent(f.Proto.GoIdent), "); ok {")
			varName = "x." + f.Proto.GoName
		}

		if f.Optional {
			g.P("if ", varName, " != nil {")
			varName = "*" + varName
		}

		for _, step := range f.Steps {
			genStep(g, f, step, varName)
		}

		if f.Optional {
			g.P("}")
		}

		if f.Oneof {
			g.P("}")
		}

		if f.Loop {
			g.P(`}`)
		}
	}

	g.P(`return nil`)
	g.P(`}`)

	for _, innerMsg := range msg.Nested {
		if innerMsg.IsMapEntry {
			// Do not generate validation func for map entry type
			continue
		}
		g.P()
		genValidateFunc(g, innerMsg)
	}
}

func genStep(g *protogen.GeneratedFile, f *plan.Field, step plan.Step, varName string) {
	switch s := step.(type) {
	case *plan.LegacyString:
		genLegacyStringValidator(g, f, s, varName)
	case *plan.String:
		genStringValidator(g, f, s, varName)
	case *plan.ID:
		genIdValidator(g, f, s, varName)
	case *plan.Email:
		genEmailValidator(g, f, s, varName)
	case *plan.Username:
		genUsernameValidator(g, f, s, varName)
	case *plan.URL:
		genURLValidator(g, f, s, varName)
	case *plan.Timezone:
		genTimezoneValidator(g, f, s, varName)
	case *plan.SimpleString:
		genSimpleStringValidator(g, f, s, varName)
	case *plan.Bytes:
		genBytesValidator(g, f, s, varName)
	case *plan.Int:
		genIntValidator(g, f, s, varName)
	case *plan.Number:
		genNumberValidator(g, f, s, varName)
	case *plan.MessageField:
		genMsgValidator(g, f, s, varName)
	case *plan.EnumField:
		genEnumValidator(g, f, varName)
	default:
		panic(fmt.Sprintf("no Go emitter for validation step %T", step))
	}
}

func genLegacyStringValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.LegacyString, varName string) {
	if s.Optional {
		g.P("if ", varName, " != \"\" {")
	}

	if s.MatchRegex {
		g.P("if !_regex_", f.Proto.GoIdent, ".MatchString(", varName, ") {")
		// Let's not expose the regex pattern and find a better way to reflect what was wrong with the data
		// Might want to replace with a more helpful message
		errStr := "be a string conforming to predefined pattern"
		genErrorStringWithParams(g, varName, f.Name, errStr)
		g.P("}")
	}

	// Legacy UUIDv4 validator
	if s.UUID {
		g.P("if !", s12protoPackage.Ident("IsUUID"), "(", varName, ") {")
		errStr := "be parsable as a UUID"
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}

	if s.LegacyID {
		g.P("if !", s12protoPackage.Ident("IsLegacyID"), "(", varName, ", false) {")
		errStr := "be parsable as a UUID or a legacy ID"
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}

	genLenValidator(g, f, s.Length, varName)

	if s.Optional {
		g.P("}")
	}
}

func genSimpleStringValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.SimpleString, varName string) {
	if s.Optional {
		g.P("if ", varName, " != \"\" {")
	}

	if s.Bounded {
		// Name the variable after the field, as genLenValidator does. A fixed name collides
		// as soon as one message has two non-optional length-bounded simple_string fields:
		// both declarations land in the same Validate() block and the generated code does
		// not compile.
		//
		// The prefix differs from genLenValidator's `_len_` on purpose. A StringKind field
		// runs through both, so sharing the prefix would reintroduce the same clash for a
		// field carrying both a `string` and a `simple_string` validator.
		lenVar := "_slen_" + f.Proto.GoIdent.GoName
		g.P("var "+lenVar+" = ", utfPackage.Ident("RuneCountInString"), "(", varName, ")")
		g.P("if ("+lenVar+" > ", s.MaxLen, " || "+lenVar+" < ", s.MinLen, ") {")
		errStr := fmt.Sprintf(`have a length between %d and %d`, s.MinLen, s.MaxLen)
		if s.LogOnly {
			printErrorString(g, varName, f.Name, errStr, 50)
		} else {
			genErrorString(g, varName, f.Name, errStr)
		}
		g.P("}")
	}

	if s.Optional {
		g.P("}")
	}
}

func genStringValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.String, varName string) {
	if s.Optional {
		g.P("if ", varName, " != \"\" {")
	}

	for _, op := range s.Ops {
		genStringOp(g, f, op, varName)
	}

	if s.Optional {
		g.P("}")
	}
}

func genStringOp(g *protogen.GeneratedFile, f *plan.Field, op plan.Op, varName string) {
	switch o := op.(type) {
	case *plan.OpNormalizeNFC:
		// Convert to unicode NFC if not already in that format
		g.P("if !", normPackage.Ident("NFC.IsNormalString"), "(", varName, ") && ", normPackage.Ident("NFD.IsNormalString"), "(", varName, ") {")
		g.P("// normalise NFD to NFC string")
		g.P("var normErr error")
		g.P(varName, ", _, normErr = ", transformPackage.Ident("String"), "(", transformPackage.Ident("Chain"), "(", normPackage.Ident("NFD"), ",", normPackage.Ident("NFC"), ")", ",", varName, ")")
		g.P("if normErr != nil {")
		genFailure(g, o.LogOnly, varName, f.Name, `must be normalisable to NFC`)
		g.P("}")
		g.P("}")

	case *plan.OpCheckEncoding:
		// U+FFFD in character indicates that the encoding was likely incorrect, resulting in <?> U+FFFD (RuneError)
		// Test string: $\xa35 for Pepp\xe9 which is encoded as latin1
		g.P("if ", stringsPackage.Ident("ContainsRune"), "(", varName, ", ", utfPackage.Ident("RuneError"), ") {")
		genFailure(g, o.LogOnly, varName, f.Name, `must have valid encoding`)
		// Also validate using utf8.ValidString: reports whether string consists entirely of valid UTF-8-encoded runes
		g.P("} else if !", utfPackage.Ident("ValidString"), "(", varName, ") {")
		genFailure(g, o.LogOnly, varName, f.Name, `must be a valid UTF-8-encoded string`)
		g.P("}")

	case *plan.OpRejectURL:
		g.P("if ", s12protoPackage.Ident("RejectURLMatcher"), ".MatchString(", varName, ") {")
		genErrorStringWithParams(g, varName, f.Name, "not contain a URL")
		g.P("}")

	case *plan.OpBreakPartialURL:
		g.P(varName, " = ", s12protoPackage.Ident("BreakURLMatcher"), ".ReplaceAllString(", varName, ", \". $1\")")

	case *plan.OpTrim:
		g.P(varName, " = ", stringsPackage.Ident("TrimSpace"), "(", varName, ")")

	case *plan.OpReplaceLiteral:
		g.P(varName, " = ", stringsPackage.Ident("ReplaceAll"), "(", varName, `, "\u`, goEscape(o.From), `", "\u`, goEscape(o.To), `")`)

	case *plan.OpReplaceUnsafe:
		g.P(varName, " = ", s12protoPackage.Ident("UnsafeCharReplacer"), ".Replace(", varName, ")")

	case *plan.OpStripCR:
		g.P(varName, " = ", stringsPackage.Ident("ReplaceAll"), "(", varName, ", \"\\r\", \"\")")

	case *plan.OpReplaceOther:
		if o.Multiline {
			// Should not replace \n as the normal symbol replacer does otherwise multiline breaks
			g.P(varName, " = ", s12protoPackage.Ident("SymbolCharReplacerMultiline"), ".Replace(", varName, ")")
		} else {
			g.P(varName, " = ", s12protoPackage.Ident("SymbolCharReplacer"), ".Replace(", varName, ")")
		}

	case *plan.OpStripPUA:
		g.P(varName, "= ", s12protoPackage.Ident("RegexPua"), ".ReplaceAllString(", varName, ", \"\")")

	case *plan.OpLength:
		// Determine which length check method to use: bytes or runes
		lenVar := "_len_" + f.Proto.GoIdent.GoName
		if o.Runes {
			g.P("var "+lenVar+" = ", utfPackage.Ident("RuneCountInString"), "(", varName, ")")
		} else {
			g.P("var "+lenVar+" = len(", varName, ")")
		}

		errStr := ""
		if o.Min == o.Max {
			g.P("if !("+lenVar+" == ", o.Min, ") {")
			errStr = fmt.Sprintf(`have length %d`, o.Min)
		} else {
			g.P("if !("+lenVar+" >= ", o.Min, " && "+lenVar+" <= ", o.Max, ") {")
			errStr = fmt.Sprintf(`have a length between %d and %d`, o.Min, o.Max)
		}
		genFailure(g, o.LogOnly, varName, f.Name, errStr)
		g.P("}")

	case *plan.OpHasPrefix:
		g.P("if !", stringsPackage.Ident("HasPrefix"), "(", varName, ", \"", o.Prefix, "\") {")
		genErrorString(g, varName, f.Name, "start with prefix")
		g.P("}")

	case *plan.OpMatchPattern:
		regexName := addRegexVar(f.Proto.GoIdent.GoName, o.Pattern)
		g.P("if !_regex_", regexName, ".MatchString(", varName, ") {")
		// Might want to improve the error message: make it more helpful so the end-user can fix it if applicable
		errStr := "only have valid characters"
		if o.LogOnly {
			printErrorString(g, varName, f.Name, errStr, 50)
		} else {
			genErrorStringWithParams(g, varName, f.Name, errStr)
		}
		g.P("}")

	default:
		panic(fmt.Sprintf("no Go emitter for string operation %T", op))
	}
}

// goEscape renders a character as the digits of a Go \u escape.
func goEscape(r rune) string {
	return fmt.Sprintf("%04X", r)
}

func genIdValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.ID, varName string) {
	if s.Optional {
		g.P("if ", varName, " != \"\" {")
	}

	switch s.Version {
	case "v4":
		g.P("if !", s12protoPackage.Ident("IsUUIDv4"), "(", varName, ") {")
	case "any":
		g.P("if !", s12protoPackage.Ident("IsUUID"), "(", varName, ") {")
	}

	// Invalid UUID: check other formats or error if no other options enabled
	g.P("isValidId := false")

	if s.Legacy {
		g.P("if ", s12protoPackage.Ident("IsLegacyID"), "(", varName, ", ", s.LowercaseOnly, ") {")
		g.P("isValidId = true")
		g.P("}")
	}

	if s.S12 {
		g.P("if !isValidId && ", s12protoPackage.Ident("IsS12ID"), "(", varName, ", ", s.LowercaseOnly, ") {")
		g.P("isValidId = true")
		g.P("}")
	}

	if s.LongPrefixed {
		g.P("if !isValidId && ", s12protoPackage.Ident("IsLongPrefixedLegacyID"), "(", varName, ") {")
		g.P("isValidId = true")
		g.P("}")
	}

	// Check if any of the validations passed
	g.P("if !isValidId {")
	genFailure(g, s.LogOnly, varName, f.Name, s.Requirement)

	g.P("}")
	g.P("}")

	if s.Optional {
		g.P("}")
	}
}

func genEmailValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.Email, varName string) {
	if s.Optional {
		g.P("if ", varName, " != \"\" {")
	}

	checkDomain := false // rules.GetCheckDomain() == true

	// Validate the value for valid email using govalidator validation package
	g.P("if !", s12protoPackage.Ident("IsValidEmail"), "(", varName, ", ", checkDomain, ") {")
	// Should not return/log email address as this is PII (genErrorString will no longer reflect values)
	genErrorString(g, varName, f.Name, "be parsable as an email address")
	g.P("}")

	if s.Optional {
		g.P("}")
	}
}

// genUsernameValidator emits validation for the (validator.username) annotation:
// the value must be a valid email, or (when allow_non_email is set) a valid
// non-email username. Like the email validator, the value is not reflected in
// the error since it may be PII.
func genUsernameValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.Username, varName string) {
	if s.Optional {
		g.P("if ", varName, " != \"\" {")
	}

	g.P("if !", s12protoPackage.Ident("IsValidEmail"), "(", varName, ", false) {")
	g.P("isValidUsername := false")
	if s.AllowNonEmail {
		g.P("if ", s12protoPackage.Ident("IsValidNonEmail"), "(", varName, ") {")
		g.P("isValidUsername = true")
		g.P("}")
	}
	g.P("if !isValidUsername {")
	genFailure(g, s.LogOnly, varName, f.Name, "be a valid email address or username")
	g.P("}")
	g.P("}")

	if s.Optional {
		g.P("}")
	}
}

func genURLValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.URL, varName string) {
	if s.Optional {
		g.P("if ", varName, " != \"\" {")
	}

	// Validate the url using the helper method
	g.P(`_schemes_`+f.Proto.GoIdent.GoName+` := []string{"`, strings.Join(s.Schemes, `", "`), `"}`)
	g.P("if _, err := ", s12protoPackage.Ident("IsValidURL"), "(", varName, ", _schemes_"+f.Proto.GoIdent.GoName+", ", s.AllowFragment, "); err != nil {")
	genErrorStringWithParams(g, varName, f.Name, "be parsable as a URL: %v", "err")
	g.P("}")

	if s.Optional {
		g.P("}")
	}
}

func genTimezoneValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.Timezone, varName string) {
	if s.Optional {
		g.P("if ", varName, " != \"\" {")
	} else {
		g.P("if ", varName, " == \"\" {")
		g.P("return ", fmtPackage.Ident("Errorf"), "(\"field ", f.Name, " is required\")")
		g.P("}")
	}

	g.P("if tz, err := ", timePackage.Ident("LoadLocation"), "(", varName, "); err != nil || tz == nil {")
	errStr := "be a valid IANA TZ database value"
	genErrorStringWithParams(g, varName, f.Name, errStr)
	g.P("}")

	if s.Optional {
		g.P("}")
	}
}

func genLenValidator(g *protogen.GeneratedFile, f *plan.Field, l *plan.Length, varName string) {
	if l == nil {
		return
	}

	if l.TrimFirst {
		g.P("_trim_", f.Proto.GoIdent, " := ", stringsPackage.Ident("TrimSpace"), "(", varName, ")")
		varName = "_trim_" + f.Proto.GoIdent.GoName
		g.P("_ = ", varName)
	}

	if v := l.Gte; v >= 0 {
		g.P("if !(len(", varName, ") >= ", v, ") {")
		errStr := fmt.Sprintf(`have length greater than or equal to %d`, v)
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}

	if v := l.Lte; v >= 0 {
		g.P("if !(len(", varName, ") <= ", v, ") {")
		errStr := fmt.Sprintf(`have length less than or equal to %d`, v)
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}
}

func genBytesValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.Bytes, varName string) {
	if s.Optional {
		g.P("if ", varName, " != nil && len(", varName, ") > 0 {")
	}

	if s.UUIDSize {
		g.P("if len(", varName, ") != ", s12protoPackage.Ident("UUIDSize"), " {")
		errStr := "be exactly 16 bytes long to be a valid UUID"
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}

	genLenValidator(g, f, s.Length, varName)

	if s.Optional {
		g.P("}")
	}
}

func genIntValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.Int, varName string) {
	if s.Optional {
		g.P("if ", varName, " != 0 {")
	}

	if v := s.Gt; v >= 0 {
		g.P("if !(", varName, " > ", v, ") {")
		errStr := fmt.Sprintf(`be greater than %d`, v)
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}
	if v := s.Gte; v >= 0 {
		g.P("if !(", varName, " >= ", v, ") {")
		errStr := fmt.Sprintf(`be greater than or equal to %d`, v)
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}
	if v := s.Lt; v >= 0 {
		g.P("if !(", varName, " < ", v, ") {")
		errStr := fmt.Sprintf(`be less than %d`, v)
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}
	if v := s.Lte; v >= 0 {
		g.P("if !(", varName, " <= ", v, ") {")
		errStr := fmt.Sprintf(`be less than or equal to %d`, v)
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}

	if s.Optional {
		g.P("}")
	}
}

func genNumberValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.Number, varName string) {
	if s.Optional {
		g.P("if ", varName, " != 0 {")
	}

	if s.RejectNaN {
		g.P("// This statement checks for NaN value without using Math package")
		g.P("if ", varName, " != ", varName, " {")
		errStr := "not be NaN"
		genErrorString(g, varName, f.Name, errStr)
		g.P("}")
	}

	if s.Min != "" {
		g.P("// Range check lower bounds")
		g.P("if ", varName, " < ", s.Min, " {")
		errStr := fmt.Sprintf("be greater than or equal to %v", s.Min)
		genFailure(g, s.LogOnly, varName, f.Name, errStr)
		g.P("}")
	}

	if s.Max != "" {
		g.P("// Range check upper bounds")
		g.P("if ", varName, " > ", s.Max, " {")
		errStr := fmt.Sprintf("be less than or equal to %v", s.Max)
		genFailure(g, s.LogOnly, varName, f.Name, errStr)
		g.P("}")
	}

	if s.Optional {
		g.P("}")
	}
}

func genMsgValidator(g *protogen.GeneratedFile, f *plan.Field, s *plan.MessageField, varName string) {
	if s.Required {
		g.P("if ", varName, " == nil {")
		g.P("return ", fmtPackage.Ident("Errorf"), "(\"field ", f.Name, " is required\")")
		g.P("}")
	}

	// For repeated messages, we need to run the validator on each message instead of this field
	if s.Repeated {
		// Please leave the len check in place here as I have identified edge cases where it is required (will add test case for it later)
		g.P("if len(", varName, ") > 0 {")
		g.P("for _, item := range ", varName, "{")
		varName = "item"
	}

	g.P("if ", varName, " != nil {")
	g.P("if v, ok := interface{}(", varName, ").(", s12protoPackage.Ident("Validator"), "); ok {")
	g.P("if err := v.Validate(); err != nil {")
	g.P("return ", s12protoPackage.Ident("FieldError"), "(\"", f.Name, "\", err)")
	g.P("}")
	g.P("}")
	g.P("}")

	if s.Repeated {
		g.P("}") // for
		g.P("}") // if len
	}
}

func genEnumValidator(g *protogen.GeneratedFile, f *plan.Field, varName string) {
	g.P("if int(", varName, ") == 0 {")
	g.P("return ", fmtPackage.Ident("Errorf"), "(\"field ", f.Name, " must be specified and a non-zero value\")")
	g.P("}")
}

// genFailure writes the reaction to a failed check: a log line when the field is
// in log-only mode, and a returned error otherwise.
func genFailure(g *protogen.GeneratedFile, logOnly bool, varName, fieldName, specificErr string) {
	if logOnly {
		printErrorString(g, varName, fieldName, specificErr, 50)
		return
	}
	genErrorString(g, varName, fieldName, specificErr)
}

func printErrorString(g *protogen.GeneratedFile, varName, fieldName, specificErr string, maxLen int) {
	// Do not reflect untrusted value in error, certainly not for sensitive fields like password or PII like email
	g.P(fmtPackage.Ident("Printf"), `("[log-only] %s: value must be %s: Base64Encoded input: %s\n", `, `"`, fieldName, `", "`, specificErr, `" `, ", ",
		s12protoPackage.Ident("Base64Encode("),
		s12protoPackage.Ident("FirstCharactersFromString("),
		fmtPackage.Ident("Sprintf"), "(\"%v\", ", varName, "), ", maxLen, ")))")
}

func genErrorString(g *protogen.GeneratedFile, varName, fieldName, specificErr string) {
	// Do not reflect untrusted value in error, certainly not for sensitive fields like password or PII like email
	g.P(`return `, fmtPackage.Ident("Errorf"), "(`", fieldName, `: value must `, specificErr, "`)")
}

func genErrorStringWithParams(g *protogen.GeneratedFile, varName, fieldName, specificErr string, errParams ...string) {
	// Might want to improve the error message: make it more helpful so the end-user can fix it if applicable
	g.P(`return `, fmtPackage.Ident("Errorf"), "(`", fieldName, `: value must `, specificErr, "`, ", strings.Join(errParams, ", "), `)`)
}

func genLenErrorString(g *protogen.GeneratedFile, varName, fieldName, specificErr string) {
	g.P(`return `, fmtPackage.Ident("Errorf"), "(`", fieldName, `: length must `, specificErr, "`)")
}
