// Copyright (c) 2026 SafetyCulture Pty Ltd. All Rights Reserved.

// Package plugin emits C# validators from the shared validation plan.
package plugin

import (
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"path"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"

	"github.com/SafetyCulture/s12-proto/protobuf/protoc-gen-csharpvalidator/runtime"
	plan "github.com/SafetyCulture/s12-proto/protobuf/validation/plan"
)

const logOnlyMaxLength = 50

// Options selects which files are generated.
type Options struct {
	// Include holds path globs. A file is generated only when one of them matches,
	// so adding this plugin to a build emits nothing until a path is named.
	Include []string

	// SkipRuntime leaves out the support library the generated code calls into, for
	// a build that already compiles it from another source.
	SkipRuntime bool
}

// Generate writes the runtime and a validator file for every included input.
func Generate(p *protogen.Plugin, opts Options) error {
	p.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	plan.Reset()

	if !opts.SkipRuntime {
		if err := emitRuntime(p); err != nil {
			return err
		}
	}

	for _, file := range p.Files {
		if !file.Generate {
			continue
		}

		// Every file the run generates is built, including one that is not written.
		// The allow-list pattern pool accumulates across a run, so a field's pattern
		// depends on which files were built before it: building only the included
		// subset would give a field a different allow list here from the one the Go
		// validators give it.
		built := plan.BuildFile(file)

		included, err := includes(opts.Include, file.Desc.Path())
		if err != nil {
			return err
		}
		if !included {
			continue
		}
		if err := generateFile(p, file, built); err != nil {
			return fmt.Errorf("%s: %w", file.Desc.Path(), err)
		}
	}

	return nil
}

// includes reports whether any glob matches the proto path. A glob covers a whole
// subtree when it ends in /**.
func includes(globs []string, protoPath string) (bool, error) {
	for _, glob := range globs {
		if subtree, ok := strings.CutSuffix(glob, "/**"); ok {
			if protoPath == subtree || strings.HasPrefix(protoPath, subtree+"/") {
				return true, nil
			}
			continue
		}
		matched, err := path.Match(glob, protoPath)
		if err != nil {
			return false, fmt.Errorf("bad include pattern %q: %w", glob, err)
		}
		if matched {
			return true, nil
		}
	}
	return false, nil
}

// emitRuntime writes the runtime once per invocation, whatever the input set.
func emitRuntime(p *protogen.Plugin) error {
	files, err := runtime.Files()
	if err != nil {
		return err
	}

	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		if _, err := p.NewGeneratedFile(name, "").Write([]byte(files[name])); err != nil {
			return err
		}
	}
	return nil
}

// emitter writes one file, tracking indentation, the character classes the file
// needs, and a counter that keeps generated local names distinct.
type emitter struct {
	g        *protogen.GeneratedFile
	holder   string
	patterns map[string]string
	order    []string
	indent   int
	locals   int
}

func (e *emitter) p(args ...any) {
	var line strings.Builder
	line.WriteString(strings.Repeat("    ", e.indent))
	for _, arg := range args {
		fmt.Fprint(&line, arg)
	}
	e.g.P(strings.TrimRight(line.String(), " "))
}

func (e *emitter) open(args ...any) {
	e.p(args...)
	e.p("{")
	e.indent++
}

func (e *emitter) shut() {
	e.indent--
	e.p("}")
}

func (e *emitter) local(prefix string) string {
	e.locals++
	return fmt.Sprintf("_%s%d", prefix, e.locals)
}

// pattern declares a translated character class and returns its field name.
// Identical classes share one declaration.
func (e *emitter) pattern(pattern string) string {
	sum := md5.Sum([]byte(pattern))
	name := "Class" + hex.EncodeToString(sum[:])[:16]
	if _, found := e.patterns[name]; !found {
		e.patterns[name] = pattern
		e.order = append(e.order, name)
	}
	return name
}

func generateFile(p *protogen.Plugin, file *protogen.File, built *plan.File) error {
	if !hasMessages(built.Messages) {
		return nil
	}

	base := pascalCase(strings.TrimSuffix(path.Base(file.Desc.Path()), ".proto"))
	holder := base + "ValidatorClasses"

	// protoc names its C# output after the pascal-cased proto file, so the validator
	// sits beside it under the same name.
	name := base + "Validator.g.cs"
	if dir := path.Dir(file.GeneratedFilenamePrefix); dir != "." {
		name = dir + "/" + name
	}

	g := p.NewGeneratedFile(name, "")
	e := &emitter{g: g, holder: holder, patterns: map[string]string{}}

	e.p("// <auto-generated>")
	e.p("//     Generated by protoc-gen-csharpvalidator. DO NOT EDIT.")
	e.p("//     source: ", file.Desc.Path())
	e.p("// </auto-generated>")
	e.p("#nullable enable")
	// A rule on a field marked deprecated reads that field, which the compiler reports
	// unless the file waives it.
	e.p("#pragma warning disable 0612, 0618 // obsolete member")
	e.p()
	e.p("using System;")
	e.p("using System.Text.RegularExpressions;")
	e.p("using S12.Protobuf.Validation;")
	e.p()

	// A file with no package declaration puts its types in the global namespace.
	namespace := fileNamespace(file)
	if namespace != "" {
		e.open("namespace ", namespace)
	}

	for _, msg := range built.Messages {
		if err := emitMessage(e, msg, holder); err != nil {
			return err
		}
	}

	emitPatternHolder(e, holder)

	if namespace != "" {
		e.shut()
	}
	return nil
}

// hasMessages reports whether anything in the file would carry a validator.
func hasMessages(messages []*plan.Message) bool {
	for _, msg := range messages {
		if !msg.IsMapEntry {
			return true
		}
	}
	return false
}

// emitMessage declares the message's Validate, then recurses into the container
// protoc puts its nested messages in.
func emitMessage(e *emitter, msg *plan.Message, holder string) error {
	if msg.IsMapEntry {
		return nil
	}

	e.p()
	e.open("public sealed partial class ", messageName(msg.Proto.Desc), " : IValidatableMessage")

	e.p("/// <summary>Applies the rules declared in ", msg.Proto.Desc.ParentFile().Path(), ".</summary>")
	e.open("public ValidationError? Validate()")
	for _, field := range msg.Fields {
		if err := emitField(e, field, holder); err != nil {
			return err
		}
	}
	e.p("return null;")
	e.shut()

	nested := make([]*plan.Message, 0, len(msg.Nested))
	for _, inner := range msg.Nested {
		if !inner.IsMapEntry {
			nested = append(nested, inner)
		}
	}
	if len(nested) > 0 {
		e.p()
		e.open("public static partial class Types")
		for _, inner := range nested {
			if err := emitMessage(e, inner, holder); err != nil {
				return err
			}
		}
		e.shut()
	}

	e.shut()
	return nil
}

func emitPatternHolder(e *emitter, holder string) {
	if len(e.order) == 0 {
		return
	}

	e.p()
	e.p("/// <summary>The character classes the validators in this file check against.</summary>")
	e.open("internal static class ", holder)
	e.p("private const RegexOptions Options = RegexOptions.NonBacktracking | RegexOptions.CultureInvariant;")
	for _, name := range e.order {
		e.p()
		e.p("internal static readonly Regex ", name, " = new(", stringLiteral(e.patterns[name]), ", Options);")
	}
	e.shut()
}
