// Code generated by protoc-gen-govalidator. DO NOT EDIT.
// versions:
// 	protoc-gen-govalidator v2.7.2
// 	protoc                 v7.36.1
// source: example.proto

package example

import (
	_ "github.com/SafetyCulture/s12-proto/s12/protobuf/proto"
	regexp "regexp"
)

// Pattern for ExampleMessage_StringOptional
const _regex_val_dacd7d349b42e34a5ce4fbd057f04d72 = `^[\pL\pN\x{0020}\x{0028}\x{0029}\x{002C}\x{002E}\x{003A}\x{003F}\x{0040}\x{005B}\x{005D}\x{005F}\x{00BF}\x{2013}\x{2062}\x{2064}]+$`

var _regex_dacd7d349b42e34a5ce4fbd057f04d72 = regexp.MustCompile(_regex_val_dacd7d349b42e34a5ce4fbd057f04d72)
