// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example.proto

package example

import (
	fmt "fmt"
	_ "github.com/SafetyCulture/s12-proto/protobuf/s12proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ExampleMessage struct {
	// returns an error if the string cannot be parsed as a UUID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// bytes can also be parsed as UUID with support for gogo
	UserID []byte `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// strings can validate against a regular expresion
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// integers can be greater than a value
	Age int32 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	// integers can be less than a value
	Speed int64 `protobuf:"varint,5,opt,name=speed,proto3" json:"speed,omitempty"`
	// integers greater/less than or equal, the can also be combined
	Score int32 `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	// validation is created for all messages
	Inner *InnerMessage `protobuf:"bytes,7,opt,name=inner,proto3" json:"inner,omitempty"`
	// can validate each repeated item too
	Ids [][]byte `protobuf:"bytes,8,rep,name=ids,proto3" json:"ids,omitempty"`
	// only validate if non-zero value
	MediaId string `protobuf:"bytes,9,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	// validate the max length of a string
	Description string `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	// validate the min length
	Password string `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	// You don't need to validate everything
	NoValidation string `protobuf:"bytes,12,opt,name=no_validation,json=noValidation,proto3" json:"no_validation,omitempty"`
	// Types that are valid to be assigned to ContactOneof:
	//	*ExampleMessage_Fax
	//	*ExampleMessage_Phone
	ContactOneof isExampleMessage_ContactOneof `protobuf_oneof:"contact_oneof"`
	// Required inner message
	MsgRequired *InnerMessage `protobuf:"bytes,15,opt,name=msg_required,json=msgRequired,proto3" json:"msg_required,omitempty"`
	// returns an error if the string cannot be parsed as a legacy id
	LegacyID string `protobuf:"bytes,16,opt,name=legacy_id,json=legacyId,proto3" json:"legacy_id,omitempty"`
	// InnerMessage can contain a legacy id too
	InnerLegacyId *InnerMessageWithLegacyId `protobuf:"bytes,17,opt,name=inner_legacy_id,json=innerLegacyId,proto3" json:"inner_legacy_id,omitempty"`
	// Trim leading and trailing whitespaces (as defined by Unicode) before doing length check
	Name                 string   `protobuf:"bytes,18,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleMessage) Reset()         { *m = ExampleMessage{} }
func (m *ExampleMessage) String() string { return proto.CompactTextString(m) }
func (*ExampleMessage) ProtoMessage()    {}
func (*ExampleMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}
func (m *ExampleMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleMessage.Unmarshal(m, b)
}
func (m *ExampleMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleMessage.Marshal(b, m, deterministic)
}
func (m *ExampleMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleMessage.Merge(m, src)
}
func (m *ExampleMessage) XXX_Size() int {
	return xxx_messageInfo_ExampleMessage.Size(m)
}
func (m *ExampleMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleMessage proto.InternalMessageInfo

type isExampleMessage_ContactOneof interface {
	isExampleMessage_ContactOneof()
}

type ExampleMessage_Fax struct {
	Fax string `protobuf:"bytes,13,opt,name=fax,proto3,oneof" json:"fax,omitempty"`
}
type ExampleMessage_Phone struct {
	Phone string `protobuf:"bytes,14,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
}

func (*ExampleMessage_Fax) isExampleMessage_ContactOneof()   {}
func (*ExampleMessage_Phone) isExampleMessage_ContactOneof() {}

func (m *ExampleMessage) GetContactOneof() isExampleMessage_ContactOneof {
	if m != nil {
		return m.ContactOneof
	}
	return nil
}

func (m *ExampleMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExampleMessage) GetUserID() []byte {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *ExampleMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ExampleMessage) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *ExampleMessage) GetSpeed() int64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *ExampleMessage) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ExampleMessage) GetInner() *InnerMessage {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *ExampleMessage) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ExampleMessage) GetMediaId() string {
	if m != nil {
		return m.MediaId
	}
	return ""
}

func (m *ExampleMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ExampleMessage) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ExampleMessage) GetNoValidation() string {
	if m != nil {
		return m.NoValidation
	}
	return ""
}

func (m *ExampleMessage) GetFax() string {
	if x, ok := m.GetContactOneof().(*ExampleMessage_Fax); ok {
		return x.Fax
	}
	return ""
}

func (m *ExampleMessage) GetPhone() string {
	if x, ok := m.GetContactOneof().(*ExampleMessage_Phone); ok {
		return x.Phone
	}
	return ""
}

func (m *ExampleMessage) GetMsgRequired() *InnerMessage {
	if m != nil {
		return m.MsgRequired
	}
	return nil
}

func (m *ExampleMessage) GetLegacyID() string {
	if m != nil {
		return m.LegacyID
	}
	return ""
}

func (m *ExampleMessage) GetInnerLegacyId() *InnerMessageWithLegacyId {
	if m != nil {
		return m.InnerLegacyId
	}
	return nil
}

func (m *ExampleMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExampleMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExampleMessage_Fax)(nil),
		(*ExampleMessage_Phone)(nil),
	}
}

type InnerMessage struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerMessage) Reset()         { *m = InnerMessage{} }
func (m *InnerMessage) String() string { return proto.CompactTextString(m) }
func (*InnerMessage) ProtoMessage()    {}
func (*InnerMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}
func (m *InnerMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMessage.Unmarshal(m, b)
}
func (m *InnerMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMessage.Marshal(b, m, deterministic)
}
func (m *InnerMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMessage.Merge(m, src)
}
func (m *InnerMessage) XXX_Size() int {
	return xxx_messageInfo_InnerMessage.Size(m)
}
func (m *InnerMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMessage proto.InternalMessageInfo

func (m *InnerMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type InnerMessageWithLegacyId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InnerMessageWithLegacyId) Reset()         { *m = InnerMessageWithLegacyId{} }
func (m *InnerMessageWithLegacyId) String() string { return proto.CompactTextString(m) }
func (*InnerMessageWithLegacyId) ProtoMessage()    {}
func (*InnerMessageWithLegacyId) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}
func (m *InnerMessageWithLegacyId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InnerMessageWithLegacyId.Unmarshal(m, b)
}
func (m *InnerMessageWithLegacyId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InnerMessageWithLegacyId.Marshal(b, m, deterministic)
}
func (m *InnerMessageWithLegacyId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InnerMessageWithLegacyId.Merge(m, src)
}
func (m *InnerMessageWithLegacyId) XXX_Size() int {
	return xxx_messageInfo_InnerMessageWithLegacyId.Size(m)
}
func (m *InnerMessageWithLegacyId) XXX_DiscardUnknown() {
	xxx_messageInfo_InnerMessageWithLegacyId.DiscardUnknown(m)
}

var xxx_messageInfo_InnerMessageWithLegacyId proto.InternalMessageInfo

func (m *InnerMessageWithLegacyId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ExampleMessage)(nil), "example.ExampleMessage")
	proto.RegisterType((*InnerMessage)(nil), "example.InnerMessage")
	proto.RegisterType((*InnerMessageWithLegacyId)(nil), "example.InnerMessageWithLegacyId")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0x9b, 0x38, 0x71, 0x5f, 0x9c, 0xa4, 0x9c, 0x00, 0x9d, 0x2a, 0xc4, 0x99, 0xb6, 0x12,
	0x91, 0xa2, 0xba, 0x50, 0x76, 0x84, 0xa2, 0x22, 0xd5, 0x12, 0x2c, 0x27, 0x01, 0x4b, 0xa5, 0xe8,
	0xea, 0xbb, 0xba, 0x27, 0xc5, 0x3e, 0xe3, 0x73, 0xa0, 0x6c, 0xcc, 0x4c, 0x8c, 0x8c, 0x8c, 0x8c,
	0x1d, 0x3b, 0x22, 0x26, 0xc6, 0x8e, 0x4c, 0x1d, 0xba, 0xfa, 0x9f, 0x40, 0x77, 0x76, 0x43, 0x91,
	0x0a, 0x5b, 0xde, 0xf7, 0xeb, 0xdd, 0xfb, 0x92, 0xc0, 0x40, 0x9c, 0xb0, 0x34, 0x9f, 0x8b, 0x30,
	0x2f, 0x54, 0xa9, 0x50, 0xaf, 0x19, 0xd7, 0xb7, 0x13, 0x59, 0x1e, 0x2f, 0x0e, 0xc3, 0x58, 0xa5,
	0x3b, 0x89, 0x4a, 0xd4, 0x8e, 0xe5, 0x0f, 0x17, 0x47, 0x76, 0xb2, 0x83, 0xfd, 0x54, 0xfb, 0xd6,
	0xb1, 0x7e, 0xbc, 0x5b, 0x83, 0xef, 0xd8, 0x5c, 0x72, 0x56, 0xaa, 0xa2, 0x66, 0x36, 0x7e, 0xb8,
	0x30, 0x7c, 0x5e, 0x87, 0xbe, 0x14, 0x5a, 0xb3, 0x44, 0xa0, 0xdb, 0xb0, 0x22, 0x39, 0x76, 0x02,
	0x67, 0xbc, 0x3a, 0xed, 0x7c, 0xac, 0x88, 0x43, 0x57, 0x24, 0x47, 0x0f, 0xa1, 0xb7, 0xd0, 0xa2,
	0x98, 0x49, 0x8e, 0x57, 0x02, 0x67, 0xec, 0x4f, 0x87, 0x97, 0x17, 0xa4, 0xfb, 0x4a, 0x8b, 0x22,
	0xda, 0xb3, 0xa2, 0xae, 0xa1, 0x23, 0x8e, 0xb6, 0xc0, 0x15, 0x29, 0x93, 0x73, 0xdc, 0xb6, 0x09,
	0xc3, 0x4f, 0x15, 0x81, 0x70, 0x72, 0xf0, 0x2c, 0x9c, 0x1c, 0x84, 0xe1, 0x84, 0xd6, 0x24, 0xba,
	0x0b, 0x6d, 0x96, 0x08, 0xdc, 0x09, 0x9c, 0xb1, 0x3b, 0xed, 0x7c, 0xae, 0x48, 0x8b, 0x1a, 0x00,
	0xad, 0x83, 0xab, 0x73, 0x21, 0x38, 0x76, 0x03, 0x67, 0xdc, 0x9e, 0x76, 0xbe, 0x54, 0x24, 0xa3,
	0x35, 0x84, 0xee, 0x83, 0xab, 0x63, 0x55, 0x08, 0xdc, 0xb5, 0x2e, 0xef, 0x6b, 0x45, 0x5a, 0xdf,
	0x2a, 0xc2, 0x69, 0x0d, 0xa3, 0x09, 0xb8, 0x32, 0xcb, 0x44, 0x81, 0x7b, 0x81, 0x33, 0xee, 0xef,
	0xde, 0x09, 0xaf, 0xca, 0x8b, 0x0c, 0xda, 0x9c, 0x47, 0x6b, 0x8d, 0x79, 0x80, 0xe4, 0x1a, 0x7b,
	0x41, 0x7b, 0xec, 0x37, 0x67, 0x1a, 0x00, 0x6d, 0x82, 0x97, 0x0a, 0x2e, 0x99, 0x39, 0x74, 0xd5,
	0x5e, 0xe0, 0x19, 0xf2, 0xbb, 0x11, 0xf4, 0x2c, 0x13, 0x99, 0x32, 0xfa, 0x5c, 0xe8, 0xb8, 0x90,
	0x79, 0x29, 0x55, 0x86, 0xc1, 0xea, 0xdc, 0xb3, 0x8a, 0x9c, 0x8f, 0xe8, 0x75, 0x06, 0x05, 0xe0,
	0xe5, 0x4c, 0xeb, 0xf7, 0xaa, 0xe0, 0xb8, 0x5f, 0x37, 0x7a, 0x5a, 0x11, 0x8f, 0x2e, 0x51, 0xb4,
	0x09, 0x83, 0x4c, 0xcd, 0x9a, 0xaf, 0xc5, 0x84, 0xf9, 0x46, 0x46, 0xfd, 0x4c, 0xbd, 0x5e, 0x62,
	0x08, 0x41, 0xfb, 0x88, 0x9d, 0xe0, 0x81, 0xa1, 0xf6, 0x5b, 0xd4, 0x0c, 0xe8, 0x1e, 0xb8, 0xf9,
	0xb1, 0xca, 0x04, 0x1e, 0x2e, 0x73, 0xfb, 0xfb, 0x2d, 0x5a, 0x83, 0xe8, 0x29, 0xf8, 0xa9, 0x4e,
	0x66, 0x85, 0x78, 0xbb, 0x90, 0x85, 0xe0, 0x78, 0xf4, 0x9f, 0x4a, 0xa6, 0x9d, 0x9f, 0xe6, 0xba,
	0x7e, 0xaa, 0x13, 0xda, 0xe8, 0xd1, 0x36, 0xac, 0xce, 0x45, 0xc2, 0xe2, 0x0f, 0xa6, 0x87, 0x35,
	0xbb, 0x61, 0xed, 0xf2, 0x82, 0x78, 0x2f, 0x2c, 0x18, 0xed, 0x9d, 0x1b, 0x87, 0x57, 0x4b, 0x22,
	0x8e, 0x22, 0x18, 0xd9, 0x5a, 0x67, 0x7f, 0x4c, 0xb7, 0xec, 0xc6, 0x07, 0x37, 0x6e, 0x7c, 0x23,
	0xcb, 0xe3, 0x26, 0x89, 0xd3, 0x81, 0x75, 0x5e, 0x8d, 0x28, 0x80, 0x4e, 0xc6, 0x52, 0x81, 0x91,
	0x5d, 0xea, 0x9f, 0x56, 0xa4, 0x7b, 0x56, 0x11, 0xf8, 0x65, 0x16, 0x5a, 0x66, 0x3a, 0x82, 0x41,
	0xac, 0xb2, 0x92, 0xc5, 0xe5, 0x4c, 0x65, 0x42, 0x1d, 0x6d, 0x6c, 0x81, 0x7f, 0x3d, 0xfd, 0xe6,
	0x5f, 0xf0, 0xc6, 0x23, 0xc0, 0xff, 0x7a, 0xc3, 0xdf, 0x8e, 0xf3, 0xc6, 0x71, 0xd8, 0xb5, 0xff,
	0x91, 0x27, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x18, 0x9b, 0x80, 0x86, 0x03, 0x00, 0x00,
}
