// Copyright (c) 2020 SafetyCulture Pty Ltd. All Rights Reserved.

package generator

import (
	"strings"

	"github.com/bufbuild/protoplugin"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"

	"github.com/SafetyCulture/s12-proto/protobuf/protoc-gen-cruxclient-go/internal/codegen"
	"github.com/SafetyCulture/s12-proto/protobuf/protoc-gen-cruxclient-go/internal/common"
)

// GenerateDjinniYAML generates the .djinni.yaml file for a proto file descriptor.
// The output is functionally equivalent to the C++ plugin's api_generator.cc
// GenerateDjinniYAML function (lines 395-491). It produces one YAML record per
// message (including nested), skipping map-entry synthetics.
func GenerateDjinniYAML(rw protoplugin.ResponseWriter, fileDesc protoreflect.FileDescriptor) {
	w := codegen.NewWriter()

	path := string(fileDesc.Path())
	baseName := common.StripProto(path)

	// Path segments for name derivation
	paths := common.Tokenize(common.StripProto(path), "/")
	dirParts := paths[:len(paths)-1]
	dir := strings.Join(dirParts, "_")

	// Domain name: paths[1] if paths[0]=="s12", else paths[0]
	domainName := paths[0]
	if paths[0] == "s12" && len(paths) > 1 {
		domainName = paths[1]
	}

	fileNameCamel := common.ToCamelCase(paths[len(paths)-1])
	mainFileName := baseName

	// Proto file options
	opts := fileDesc.Options().(*descriptorpb.FileOptions)
	javaPackage := opts.GetJavaPackage()
	objcClassPrefix := opts.GetObjcClassPrefix()
	wirePackage := common.GetWirePackage(fileDesc)

	// Comment header
	w.WL("# This file is generated by s12-proto api generator. Please DO NOT modify.")

	// Per-message YAML records
	messages := common.GetMessagesFromFile(fileDesc)
	for _, msg := range messages {
		if msg.IsMapEntry() {
			continue
		}

		messageName := common.ClassName(msg, false)
		cppTypeName := common.DotsToColons(string(msg.FullName()))
		javaMessageBoxName := common.UnderscoresToDots(messageName)
		javaMessageName := common.UnderscoresToDollar(messageName)
		javaPackageSlashes := common.DotsToSlashs(javaPackage)

		writeDjinniYAMLRecord(w, domainName, fileNameCamel, dir, baseName, mainFileName,
			messageName, cppTypeName, javaMessageBoxName, javaMessageName,
			javaPackageSlashes, javaPackage, objcClassPrefix, wirePackage)
	}

	rw.AddFile(baseName+".djinni.yaml", w.String())
}

// writeDjinniYAMLRecord writes a single YAML record for a message.
func writeDjinniYAMLRecord(w *codegen.CodeWriter,
	domainName, fileNameCamel, dir, baseName, mainFileName,
	messageName, cppTypeName, javaMessageBoxName, javaMessageName,
	javaPackageSlashes, javaPackage, objcClassPrefix, wirePackage string) {

	w.WL("---")
	w.WL("name: pb_%s_%s_%s", domainName, fileNameCamel, messageName)
	w.WL("typedef: 'record deriving(eq, ord, parcelable)'")
	w.WL("params: []")
	w.WL("prefix: 'pb'")

	w.WL("cpp:")
	w.WL("  typename: '%s'", cppTypeName)
	w.WL("  header: '\"%s.pb.h\"'", baseName)
	w.WL("  byValue: false")

	w.WL("objc:")
	w.WL("  typename: '%s%s'", objcClassPrefix, messageName)
	w.WL("  header: '\"%s_%s.pbobjc.h\"'", dir, fileNameCamel)
	w.WL("  boxed: '%s%s'", objcClassPrefix, messageName)
	w.WL("  pointer: true")
	w.WL("  hash: '%s.hash()'")

	w.WL("objcpp:")
	w.WL("  translator: 'djinni::%s::Translator'", cppTypeName)
	w.WL("  header: '\"%s.djinni.objc.h\"'", mainFileName)

	w.WL("java:")
	w.WL("  typename: '%s.%s'", javaPackage, javaMessageBoxName)
	w.WL("  boxed: '%s.%s'", javaPackage, javaMessageBoxName)
	w.WL("  reference: true")
	w.WL("  generic: false")
	w.WL("  hash: '%s.hashCode()'")

	w.WL("jni:")
	w.WL("  translator: 'djinni::%s::Translator'", cppTypeName)
	w.WL("  header: '\"%s.djinni.jni.h\"'", mainFileName)
	w.WL("  typename: jobject")
	w.WL("  typeSignature: 'L%s/%s;'", javaPackageSlashes, javaMessageName)

	if wirePackage != "" {
		w.WL("kotlin:")
		w.WL("  typename: '%s.%s'", wirePackage, javaMessageBoxName)
		w.WL("  isProtobufMessage: true")
	}
	w.WL()
}
