// Copyright (c) 2020 SafetyCulture Pty Ltd. All Rights Reserved.

package generator

import (
	"github.com/SafetyCulture/s12-proto/protobuf/protoc-gen-cruxclient-go/internal/codegen"
)

// WritePrologue writes the standard 3-line CRUX comment header.
// The source path is interpolated into the third line.
// Used by api_header.go, api_source.go, and mock.go.
// NOT used by Djinni generators (they have a different comment header).
func WritePrologue(w *codegen.CodeWriter, path string) {
	w.WL("// Generated by the CRUX Engine C++ plugin.")
	w.WL("// If you make any local change, they will be lost.")
	w.WL("// source: %s", path)
}
