// Code generated by protoc-gen-govalidator. DO NOT EDIT.
// versions:
// 	protoc-gen-govalidator v2.7.2
// 	protoc                 v6.33.0
// source: geo.proto

package valtest

import (
	_ "github.com/SafetyCulture/s12-proto/s12/protobuf/proto"
)
