// Code generated by protoc-gen-govalidator. DO NOT EDIT.
// versions:
// 	protoc-gen-govalidator v2.6.0
// 	protoc                 v4.25.3
// source: geo.proto

package valtest

import (
	_ "github.com/SafetyCulture/s12-proto/s12/protobuf/proto"
)
