// Copyright (c) 2021 SafetyCulture Pty Ltd. All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: geo.proto

package valtest

import (
	_ "github.com/SafetyCulture/s12-proto/s12/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeoValidationMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Accuracy      int32                  `protobuf:"varint,9,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoValidationMessage) Reset() {
	*x = GeoValidationMessage{}
	mi := &file_geo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoValidationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoValidationMessage) ProtoMessage() {}

func (x *GeoValidationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_geo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoValidationMessage.ProtoReflect.Descriptor instead.
func (*GeoValidationMessage) Descriptor() ([]byte, []int) {
	return file_geo_proto_rawDescGZIP(), []int{0}
}

func (x *GeoValidationMessage) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoValidationMessage) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoValidationMessage) GetAccuracy() int32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

var File_geo_proto protoreflect.FileDescriptor

const file_geo_proto_rawDesc = "" +
	"\n" +
	"\tgeo.proto\x12\avaltest\x1a\"s12/protobuf/proto/validator.proto\"\xa3\x01\n" +
	"\x14GeoValidationMessage\x12*\n" +
	"\blatitude\x18\x06 \x01(\x01B\x0e\xaa\xec\x1f\n" +
	"\b\x01\x1a\x06-90:90R\blatitude\x120\n" +
	"\tlongitude\x18\a \x01(\x01B\x12\xaa\xec\x1f\x0e\b\x01\x1a\b-180:180(\x01R\tlongitude\x12-\n" +
	"\baccuracy\x18\t \x01(\x05B\x11\xaa\xec\x1f\r\b\x01\x1a\a0:10000(\x01R\baccuracyBLZJgithub.com/SafetyCulture/s12-proto/protobuf/protoc-gen-govalidator/valtestb\x06proto3"

var (
	file_geo_proto_rawDescOnce sync.Once
	file_geo_proto_rawDescData []byte
)

func file_geo_proto_rawDescGZIP() []byte {
	file_geo_proto_rawDescOnce.Do(func() {
		file_geo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geo_proto_rawDesc), len(file_geo_proto_rawDesc)))
	})
	return file_geo_proto_rawDescData
}

var file_geo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_geo_proto_goTypes = []any{
	(*GeoValidationMessage)(nil), // 0: valtest.GeoValidationMessage
}
var file_geo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_geo_proto_init() }
func file_geo_proto_init() {
	if File_geo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geo_proto_rawDesc), len(file_geo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geo_proto_goTypes,
		DependencyIndexes: file_geo_proto_depIdxs,
		MessageInfos:      file_geo_proto_msgTypes,
	}.Build()
	File_geo_proto = out.File
	file_geo_proto_goTypes = nil
	file_geo_proto_depIdxs = nil
}
