// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: complete.proto

package s12_complete

import (
	fmt "fmt"
	_ "github.com/SafetyCulture/s12-proto/protobuf/s12proto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MsgRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRequest) Reset()         { *m = MsgRequest{} }
func (m *MsgRequest) String() string { return proto.CompactTextString(m) }
func (*MsgRequest) ProtoMessage()    {}
func (*MsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07686b0939113b7, []int{0}
}
func (m *MsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRequest.Unmarshal(m, b)
}
func (m *MsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRequest.Marshal(b, m, deterministic)
}
func (m *MsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequest.Merge(m, src)
}
func (m *MsgRequest) XXX_Size() int {
	return xxx_messageInfo_MsgRequest.Size(m)
}
func (m *MsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequest proto.InternalMessageInfo

type MsgResponse struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Completed            []*Complete `protobuf:"bytes,2,rep,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MsgResponse) Reset()         { *m = MsgResponse{} }
func (m *MsgResponse) String() string { return proto.CompactTextString(m) }
func (*MsgResponse) ProtoMessage()    {}
func (*MsgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07686b0939113b7, []int{1}
}
func (m *MsgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgResponse.Unmarshal(m, b)
}
func (m *MsgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgResponse.Marshal(b, m, deterministic)
}
func (m *MsgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgResponse.Merge(m, src)
}
func (m *MsgResponse) XXX_Size() int {
	return xxx_messageInfo_MsgResponse.Size(m)
}
func (m *MsgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgResponse proto.InternalMessageInfo

func (m *MsgResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgResponse) GetCompleted() []*Complete {
	if m != nil {
		return m.Completed
	}
	return nil
}

type Complete struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	NotEmail             string   `protobuf:"bytes,5,opt,name=not_email,json=notEmail,proto3" json:"not_email,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Word                 []string `protobuf:"bytes,7,rep,name=word,proto3" json:"word,omitempty"`
	Url                  string   `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	SingleNumber         int32    `protobuf:"varint,9,opt,name=single_number,json=singleNumber,proto3" json:"single_number,omitempty"`
	RepeatedNumber       []int64  `protobuf:"varint,10,rep,packed,name=repeated_number,json=repeatedNumber,proto3" json:"repeated_number,omitempty"`
	Lat                  int32    `protobuf:"varint,11,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  int32    `protobuf:"varint,12,opt,name=lng,proto3" json:"lng,omitempty"`
	Words                string   `protobuf:"bytes,13,opt,name=words,proto3" json:"words,omitempty"`
	Wordsn               string   `protobuf:"bytes,14,opt,name=wordsn,proto3" json:"wordsn,omitempty"`
	Intn                 int32    `protobuf:"varint,15,opt,name=intn,proto3" json:"intn,omitempty"`
	Fullname             string   `protobuf:"bytes,16,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Firstname            string   `protobuf:"bytes,17,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,18,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Paragraph            string   `protobuf:"bytes,19,opt,name=paragraph,proto3" json:"paragraph,omitempty"`
	Paragraphs           string   `protobuf:"bytes,20,opt,name=paragraphs,proto3" json:"paragraphs,omitempty"`
	Paragraphsn          string   `protobuf:"bytes,21,opt,name=paragraphsn,proto3" json:"paragraphsn,omitempty"`
	Uuid                 string   `protobuf:"bytes,22,opt,name=uuid,proto3" json:"uuid,omitempty"`
	EmailAddress         string   `protobuf:"bytes,23,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,24,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Company              string   `protobuf:"bytes,25,opt,name=company,proto3" json:"company,omitempty"`
	Brand                string   `protobuf:"bytes,26,opt,name=brand,proto3" json:"brand,omitempty"`
	Product              string   `protobuf:"bytes,27,opt,name=product,proto3" json:"product,omitempty"`
	Color                string   `protobuf:"bytes,28,opt,name=color,proto3" json:"color,omitempty"`
	Hexcolor             string   `protobuf:"bytes,29,opt,name=hexcolor,proto3" json:"hexcolor,omitempty"`
	Latitude             float64  `protobuf:"fixed64,30,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,31,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Floatn               float32  `protobuf:"fixed32,32,opt,name=floatn,proto3" json:"floatn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Complete) Reset()         { *m = Complete{} }
func (m *Complete) String() string { return proto.CompactTextString(m) }
func (*Complete) ProtoMessage()    {}
func (*Complete) Descriptor() ([]byte, []int) {
	return fileDescriptor_e07686b0939113b7, []int{2}
}
func (m *Complete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Complete.Unmarshal(m, b)
}
func (m *Complete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Complete.Marshal(b, m, deterministic)
}
func (m *Complete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Complete.Merge(m, src)
}
func (m *Complete) XXX_Size() int {
	return xxx_messageInfo_Complete.Size(m)
}
func (m *Complete) XXX_DiscardUnknown() {
	xxx_messageInfo_Complete.DiscardUnknown(m)
}

var xxx_messageInfo_Complete proto.InternalMessageInfo

func (m *Complete) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Complete) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Complete) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Complete) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Complete) GetNotEmail() string {
	if m != nil {
		return m.NotEmail
	}
	return ""
}

func (m *Complete) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Complete) GetWord() []string {
	if m != nil {
		return m.Word
	}
	return nil
}

func (m *Complete) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Complete) GetSingleNumber() int32 {
	if m != nil {
		return m.SingleNumber
	}
	return 0
}

func (m *Complete) GetRepeatedNumber() []int64 {
	if m != nil {
		return m.RepeatedNumber
	}
	return nil
}

func (m *Complete) GetLat() int32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Complete) GetLng() int32 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *Complete) GetWords() string {
	if m != nil {
		return m.Words
	}
	return ""
}

func (m *Complete) GetWordsn() string {
	if m != nil {
		return m.Wordsn
	}
	return ""
}

func (m *Complete) GetIntn() int32 {
	if m != nil {
		return m.Intn
	}
	return 0
}

func (m *Complete) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *Complete) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Complete) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *Complete) GetParagraph() string {
	if m != nil {
		return m.Paragraph
	}
	return ""
}

func (m *Complete) GetParagraphs() string {
	if m != nil {
		return m.Paragraphs
	}
	return ""
}

func (m *Complete) GetParagraphsn() string {
	if m != nil {
		return m.Paragraphsn
	}
	return ""
}

func (m *Complete) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Complete) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *Complete) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Complete) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Complete) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Complete) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Complete) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Complete) GetHexcolor() string {
	if m != nil {
		return m.Hexcolor
	}
	return ""
}

func (m *Complete) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Complete) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Complete) GetFloatn() float32 {
	if m != nil {
		return m.Floatn
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgRequest)(nil), "s12.complete.MsgRequest")
	proto.RegisterType((*MsgResponse)(nil), "s12.complete.MsgResponse")
	proto.RegisterType((*Complete)(nil), "s12.complete.Complete")
}

func init() { proto.RegisterFile("complete.proto", fileDescriptor_e07686b0939113b7) }

var fileDescriptor_e07686b0939113b7 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x4d, 0x6f, 0xdb, 0x36,
	0x18, 0xc7, 0x47, 0x2b, 0x7e, 0x7b, 0xe4, 0x38, 0x0e, 0x97, 0x25, 0x8c, 0xf3, 0xc6, 0x39, 0xc3,
	0xa2, 0x61, 0x80, 0xb7, 0x38, 0x3b, 0xec, 0xb8, 0x2d, 0x18, 0xda, 0x4b, 0x8a, 0x82, 0xb9, 0xe4,
	0x96, 0x2a, 0x16, 0x23, 0x0b, 0x95, 0x49, 0x95, 0xa4, 0xda, 0xe4, 0xd6, 0x63, 0x8f, 0xbd, 0x14,
	0xe8, 0xb9, 0xa7, 0xde, 0xfc, 0x9d, 0xfc, 0x49, 0x0a, 0x51, 0x92, 0xe9, 0xa2, 0xbd, 0xf1, 0xf9,
	0xfd, 0x7f, 0xfa, 0x4b, 0x36, 0x09, 0x42, 0x7f, 0x2a, 0xe7, 0x59, 0xca, 0x0d, 0x1f, 0x67, 0x4a,
	0x1a, 0x89, 0x7b, 0xfa, 0x7c, 0x32, 0xae, 0xd9, 0x70, 0x4f, 0x9f, 0x4f, 0x2c, 0xff, 0x23, 0x56,
	0xd9, 0x74, 0x2e, 0xa7, 0x2f, 0x4b, 0x6d, 0xd4, 0x03, 0xb8, 0xd2, 0x31, 0xe3, 0xaf, 0x72, 0xae,
	0xcd, 0xe8, 0x1a, 0x7c, 0x3b, 0xe9, 0x4c, 0x0a, 0xcd, 0x71, 0x1f, 0x1a, 0x49, 0x44, 0x10, 0x45,
	0x41, 0x97, 0x35, 0x92, 0x08, 0xff, 0x05, 0xdd, 0xba, 0x31, 0x22, 0x0d, 0xea, 0x05, 0xfe, 0x64,
	0x77, 0xbc, 0xfe, 0x9e, 0xf1, 0x65, 0xb5, 0x60, 0x4e, 0x1c, 0x7d, 0xe8, 0x40, 0xa7, 0xe6, 0xdf,
	0x54, 0x5e, 0x40, 0x4b, 0x9b, 0xd0, 0xe4, 0x9a, 0x34, 0x0a, 0xf6, 0xdf, 0xc1, 0x72, 0x41, 0xf7,
	0xc0, 0x4f, 0x04, 0xcd, 0x94, 0x8c, 0x15, 0xd7, 0x1a, 0x3a, 0x75, 0x15, 0xab, 0x54, 0x4c, 0xc1,
	0x8f, 0xb8, 0x9e, 0xaa, 0x24, 0x33, 0x89, 0x14, 0xc4, 0xb3, 0x6d, 0xeb, 0x08, 0xef, 0x40, 0x93,
	0xcf, 0xc3, 0x24, 0x25, 0x1b, 0x36, 0x2b, 0x07, 0x7c, 0x0a, 0x5d, 0x21, 0xcd, 0x6d, 0x99, 0x34,
	0xed, 0xfb, 0x5a, 0xcb, 0x05, 0x6d, 0x0c, 0x10, 0xeb, 0x08, 0x69, 0xfe, 0xb7, 0xd2, 0x0e, 0x34,
	0xb3, 0x99, 0x14, 0x9c, 0xb4, 0xca, 0x47, 0xed, 0x80, 0x31, 0x6c, 0xbc, 0x91, 0x2a, 0x22, 0x6d,
	0xea, 0x05, 0x5d, 0x66, 0xd7, 0x78, 0x00, 0x5e, 0xae, 0x52, 0xd2, 0xb1, 0x5e, 0xb1, 0xc4, 0xa7,
	0xb0, 0xa9, 0x13, 0x11, 0xa7, 0xfc, 0x56, 0xe4, 0xf3, 0x3b, 0xae, 0x48, 0x97, 0xa2, 0xa0, 0xc9,
	0x7a, 0x25, 0x7c, 0x66, 0x19, 0x3e, 0x83, 0x2d, 0xc5, 0x33, 0x1e, 0x1a, 0x1e, 0xd5, 0x1a, 0x50,
	0x2f, 0xf0, 0x58, 0xbf, 0xc6, 0x95, 0x38, 0x00, 0x2f, 0x0d, 0x0d, 0xf1, 0x6d, 0x47, 0xb1, 0xb4,
	0x44, 0xc4, 0xa4, 0x57, 0x11, 0x11, 0xe3, 0x43, 0x68, 0x16, 0xdf, 0xa2, 0xc9, 0xa6, 0xfb, 0x39,
	0x04, 0xb1, 0x12, 0xe2, 0x63, 0x68, 0xd9, 0x85, 0x20, 0x7d, 0x17, 0x53, 0x60, 0x15, 0xc5, 0x43,
	0xd8, 0x48, 0x84, 0x11, 0x64, 0xab, 0x28, 0x2c, 0xd3, 0xa0, 0xc9, 0x2c, 0xc3, 0x23, 0xe8, 0xdc,
	0xe7, 0x69, 0x2a, 0xc2, 0x39, 0x27, 0x03, 0xf7, 0xf4, 0x9f, 0x88, 0xad, 0x38, 0xfe, 0x05, 0xba,
	0xf7, 0x89, 0xd2, 0xc6, 0x4a, 0xdb, 0x4e, 0xfa, 0x1b, 0x31, 0x17, 0x14, 0x4d, 0x69, 0x58, 0x49,
	0xd8, 0x49, 0xff, 0x20, 0xb6, 0xe2, 0x45, 0x53, 0x16, 0xaa, 0x30, 0x56, 0x61, 0x36, 0x23, 0x3f,
	0x3a, 0xe9, 0x29, 0x62, 0x2e, 0xc0, 0xbf, 0x02, 0xac, 0x06, 0x4d, 0x76, 0x9c, 0xf6, 0x1c, 0xb1,
	0xb5, 0x04, 0x07, 0xe0, 0xbb, 0x49, 0x90, 0x9f, 0x9c, 0x78, 0xd3, 0x60, 0xeb, 0x51, 0xf1, 0x0f,
	0xe4, 0x79, 0x12, 0x91, 0x5d, 0xa7, 0xbc, 0x40, 0xcc, 0x32, 0xfc, 0x3b, 0x6c, 0xda, 0xa3, 0x72,
	0x1b, 0x46, 0x51, 0x71, 0x12, 0xc9, 0x9e, 0x93, 0x66, 0x88, 0xf5, 0x6c, 0xf8, 0x6f, 0x99, 0xe1,
	0xdf, 0xa0, 0x67, 0x4f, 0x4a, 0xbd, 0xa5, 0xc4, 0xb9, 0x19, 0x62, 0xbe, 0xcd, 0xaa, 0x7d, 0xa5,
	0xd0, 0x2e, 0x8e, 0x74, 0x28, 0x1e, 0xc9, 0xbe, 0xb3, 0x1e, 0x10, 0xab, 0x31, 0x3e, 0x82, 0xe6,
	0x9d, 0x0a, 0x45, 0x44, 0x86, 0x36, 0x6f, 0x2f, 0x17, 0xd4, 0x7b, 0x8b, 0x10, 0x2b, 0x29, 0xfe,
	0x19, 0xda, 0x99, 0x92, 0x51, 0x3e, 0x35, 0xe4, 0xc0, 0x09, 0xef, 0x10, 0x62, 0x35, 0x2f, 0x1a,
	0xa6, 0x32, 0x95, 0x8a, 0x1c, 0x3a, 0xe1, 0x7d, 0xd1, 0x60, 0x29, 0x3e, 0x83, 0xce, 0x8c, 0x3f,
	0x94, 0xc6, 0x91, 0x35, 0xfc, 0xe5, 0x82, 0xb6, 0x3f, 0x22, 0xf4, 0x09, 0xa1, 0x53, 0xb6, 0x0a,
	0xf1, 0xb0, 0xd8, 0x3b, 0x93, 0x98, 0x3c, 0xe2, 0xe4, 0x98, 0xa2, 0xc0, 0xee, 0x59, 0x39, 0xe3,
	0x43, 0xe8, 0xa6, 0x52, 0xc4, 0x65, 0x78, 0x62, 0x43, 0x07, 0xf0, 0x09, 0xb4, 0xee, 0x53, 0x19,
	0x1a, 0x41, 0x28, 0x45, 0x41, 0xa3, 0xfc, 0x84, 0xcf, 0xc8, 0x63, 0x15, 0x9e, 0xdc, 0xc0, 0xf6,
	0xd5, 0x63, 0x7d, 0x31, 0x5c, 0x73, 0xf5, 0x3a, 0x99, 0x72, 0x7c, 0x09, 0xf0, 0x84, 0x9b, 0x2b,
	0xae, 0x75, 0x18, 0x73, 0x4c, 0xbe, 0xbe, 0x5d, 0xdc, 0x4d, 0x35, 0xdc, 0xff, 0x4e, 0x52, 0xde,
	0x5a, 0xa3, 0x1f, 0xee, 0x5a, 0xf6, 0x6e, 0xbb, 0xf8, 0x12, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xc0,
	0xd7, 0x0e, 0x14, 0x05, 0x00, 0x00,
}
